import requests
class Client():
	def __init__(self):
		self.api="http://htmlweb.ru"
	def blocklist_domain(self,domain):
		return requests.get(f"{self.api}/analiz/api.php?bl&url={domain}&json").json()
	def dns_domain(self,domain):
		return requests.get(f"{self.api}/analiz/api.php?dns&url={domain}&json").json()
	def domain_to_ip(self,domain):
		return requests.get(f"{self.api}/analiz/api.php?ip&url={domain}&json").json()
	def ogrn(self,ogrn):
		return requests.get(f"{self.api}/json/service/org?ogrn={ogrn}").json()
	def inn(self,inn):
		return requests.get(f"{self.api}/json/service/org?inn={inn}").json()
	def get_auto(self,id):
		return requests.get(f"{self.api}/json/service/car?marka={id}").json()
	def tomezone(self,country,longitude,latitude):
		return requests.get(f"{self.api}/json/geo/timezone?latitude={latitude}&longitude={longitude}&country={country}").json()
	def region_info(self,country,id):
		return requests.get(f"{self.api}/geo/api.php?country={country}&id={id}&json").json()
	def get_regions(self,country):
		return requests.get(f"{self.api}/geo/api.php?country=ru&json").json()
	def get_lokation(self,lokation:str=None):
		if location:return requests.get(f"{self.api}/geo/api.php?location={lokation}&json").json()
		else:return requests.get(f"{self.api}/geo/api.php?location&json").json()
	def phone_info(self,num):
		return requests.get(f"{self.api}/geo/api.php?json&telcod={num}").json()
	def def_phone(self,num):
		return requests.get(f"{self.api}/json/phone/def/{num}").json()
	def search_city(self,city):
		return requests.get(f"{self.api}/json/geo/search?search={city}").json()
	def sinonim(self,sinonim):
		return requests.get(f"{self.api}/json/geo/sinonim?sinonim={sinonim}").json()
	def city_longitude(self,city1,city2):
		return requests.get(f"{self.api}/geo/api.php?city1={city1}&city2={city2}&json").json()
	def city_coming(self,latitude,longitude):
		return  requests.get(f"{self.api}/api/geo/city_coming/?latitude={latitude}&longitude={longitude}&json").json()
	def ip_info(self,ip):
		return requests.get(f"{self.api}/geo/api.php?json&ip={ip}").json()
	def get_useragent_info(self,useragent):
		return  requests.get(f"{self.api}/service/api.php?json&browser={useragent}").json()
	def ip_spam_check(self,ip):
		return requests.get(f"{self.api}/json/mail/ip_spam_check?ip={ip}").json()
	def scan_ip(self,ip):
		return requests.get(f"{self.api}/json/proxy/scan_ip?ip={ip}").json()
	def num_to_text(self,num):
		return requests.get(f"{self.api}/convert/num2str?num={num}").json()
	def text_to_date(self,text):
		return requests.get(f"{self.api}/json/convert/str2date?str={text}&time_format=d.m.Y").json()
	def text_analiz(self,text):
		return requests.get(f"{self.api}/json/semantic/analiz/?text={text}").json()
	def partofspeech(self,partofspeech):
		return requests.get(f"{self.api}/json/service/partofspeech?partofspeech={partofspeech}").json()
	def grammems(self,grammems):
		return requests.get(f"{self.api}/json/service/grammems/?grammems={grammems}").json()
	def sex_name(self,name):
		return requests.get(f"{self.api}/json/service/sex?sex={name}").json()
	def inflect(self,inflect,grammems,partofspeech):
		return requests.get(f"{self.api}/json/service/inflect?inflect={inflect}&partofspeech={partofspeech}&grammems={grammems}&info").json()
	def city_info(self,city):
		return requests.get(f"{self.api}/geo/api.php?json&city_name={city}").json()
	def get_proxy(self):
		return requests.get(f"{self.api}/json/proxy/get").json()
	def get_phone_info(self,phone: str):
		return requests.get(f"{self.api}/geo/api.php?json&telcod={phone}").json()
	def get_url_info(self,url:str):
		return requests.get(f"{self.api}/analiz/api.php?whois&url={url}&json").json()
	def create_qr(self,content: str):
		return requests.get(f"{self.api}/api/service/qr/?data={content}").text